config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  get 'about', to: 'pages#about'
  get 'contacts', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
  
  get 'tags/:tag', to: 'products#index', as: :tag


  post 'line_items/:id/add', to: 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items', to: 'line_items#create'
  get 'line_items/:id', to: 'line_items#show', as: 'line_item'
  delete 'line_items/:id', to: 'line_items#destroy'


  get "profile", to: "pages#profile", as: "profile"

  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content d-flex justify-content-around">
    <div class="footer-section-contact flex-column align-items-center">
      <p><i class="fas fa-home mr-1"></i> Lisbon, Portugal</p>
      <p><i class="fas fa-envelope mr-1"></i> artequecura@gmail.com</p>
    </div>
    <div class="footer-section-social-media">
      <div class="social-media-links d-flex justify-content-center">
        <a class="fab fa-facebook-f" href="#" target="blank"></a>
        <a class="fab fa-instagram" href="#" target="blank"></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to image_tag("logonavbar.png"), root_path, class: "navbar-brand"  %>


<div class="navbar-options">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Produtos", products_path, class: "nav-link nav-topic" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sobre nós", about_path, class: "nav-link nav-topic" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contactos", contacts_path, class: "nav-link nav-topic" %>
      </li>
    </ul>
  </div>
</div>


<div class="login-menu">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <!-- <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
       
        <li class="cart">
         <%= link_to image_tag("output-onlinepngtools.png"),cart_path(:cart_id) %>
  
        </li>
        <li class="nav-item dropdown">
         <%= image_tag "other_avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Perfil", profile_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      <% if user_signed_in? && current_user.admin == true %>
            <li class="nav-item">
              <%= link_to "Admin", rails_admin_path, class: "nav-link nav-topic" %>
            </li>
             <li class="nav-item">
              <%= link_to "Orders", orders_path, class: "nav-link nav-topic" %>
            </li>
      <% end %>
    </ul>
   </div>
  </div>
</div>