config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  get 'about', to: 'pages#about'
  get 'contacts', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
  
  get 'tags/:tag', to: 'products#index', as: :tag


  post 'line_items/:id/add', to: 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items', to: 'line_items#create'
  get 'line_items/:id', to: 'line_items#show', as: 'line_item'
  delete 'line_items/:id', to: 'line_items#destroy'


  get "profile", to: "pages#profile", as: "profile"

  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  #belongs_to :product

  has_many :line_items, dependent: :destroy

  #monetize :amount_cents

  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
    # @orders = current_user.orders
  end

  def show
    @order = current_user.orders.find(params[:id])
   
  end

  def new
    @order = Order.new
  end

  def create
    cart = Cart.find(params[:cart_id])
    order = Order.create!(state: 'pending', user: current_user)
    order.line_items = cart.line_items
    line_items = []
    order.line_items.each do |item|
      line_items.push({
        name: item.product.name,
        images: [item.product.photo.key],
        amount: item.product.price_cents,
        currency: 'eur',
        quantity: item.quantity
        })
    end

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      mode: 'payment',
      line_items: line_items,
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :pay_method)

  end

  def line_items

  end
end

app/views/orders/index.html.erb
<div class="container">
  <h1>Orders</h1>
  <div class="row">
    <% @orders.each do |order| %>
      <div class="col-6 col-md-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= "Order ##{order.id}" %></h5>
            <p class="card-text"><%= "State: #{order.state}" %></p>
            <%= link_to "More details", order_path(order), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="showfullpage">
<div class="container" style="margin-top: 5%">
  <div class="row py-4">
    <div class="col-md-3"></div>
    <div class="col">
      <h1>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>

        <h3><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></h3>
            <h2>TOTAL: <%=  humanized_money_with_symbol(@order.sub_total) %></h2>
          <div class="show_box">
           <div class="items_display">
             <% @order.line_items.each do |item| %>

             <ul>
               <table class="table-light">
                <th>
                 <%= cl_image_tag item.product.photo.key, height: 100, width: 200, crop: :thumb %>
                <ul>Artigo: <%= item.product.name %></ul>
                <ul>Preço: <%= humanized_money_with_symbol(item.product.price) %></ul>
                <ul>Quantidade: <%= item.quantity %></ul>
                </th>
                </table>
             </ul>

             <% end %>
             </div>
           <div class="sub_total">
             <p><strong>Nome:</strong> <%= current_user.first_name %> <%= current_user.last_name %></p>
             <p><strong>Morada:</strong> <%= current_user.address %></p>
             <p><strong>Telefone:</strong> <%= current_user.phone_number %></p>
             <p><strong>E-Mail:</strong> <%= current_user.email %></p>
           </div>
          </div>
            <br>
      <h5>Obrigado pela sua compra; confirme o pagamento na sua área pessoal e será contactado(a) após envio.</h5>
    </div>
  </div>
</div>

<div class="container mt-2" style="margin-bottom: 10%">
  <div class="row d-flex justify-content-center">
    <div class="col-align-self-center">
      <div style="margin-top: 7em">
            <%= link_to "Back", products_path, class: "btn btn-outline-dark"%>
      </div>
    </div>
  </div>
</div>

</div>