config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  get 'about', to: 'pages#about'
  get 'contacts', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
  
  get 'tags/:tag', to: 'products#index', as: :tag


  post 'line_items/:id/add', to: 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items', to: 'line_items#create'
  get 'line_items/:id', to: 'line_items#show', as: 'line_item'
  delete 'line_items/:id', to: 'line_items#destroy'


  get "profile", to: "pages#profile", as: "profile"

  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :destroy]

  def show
  end

  def destroy
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  def set_cart
    @cart = @current_cart
  end
end

app/views/carts/show.html.erb
<div class="showfullpage">


<div class="row d-flex justify-content-center" style="margin-top: 5%">
  <h2>O meu Carrinho</h2>
</div>

<% if @cart.line_items.empty?  %>
 <div class="empty_cart" style="margin-top: 15em">
   <h3>O seu Carrinho está vazio</h3>
 </div>
 <% else %>
<div class="show_box" style="margin-top: 5%">
   <div class="items_display">
      <% @cart.line_items.each do |line_item| %>
      <ul>
       <table class="table-light">
        <th>
         <%= cl_image_tag line_item.product.photo.key, height: 100, width: 200, crop: :thumb %>
        <ul>Artigo: <%= line_item.product.name %></ul>
        <ul>Preço: <%= humanized_money_with_symbol(line_item.product.price) %></>
        <ul>Quantidade: <%= line_item.quantity %></ul>
        <ul style="list-style-type:circle">
          <li>
            <%= link_to "+1", line_item_add_path(line_item), method: :post, class: "btn-grey btn-sm" %>
            <%= link_to "-1", line_item_reduce_path(line_item), method: :post, class: "btn-grey btn-sm" %>
          </li>
          <li>
            <%= link_to "Remover item", line_item_path(line_item), method: :delete %>
          </li>
        </ul>
        </th>
        </table>
       </ul>
      <% end %>
    </div>

    <div class="sub_total" style="text-align: center;">
      <h3>Sub total: <%= humanized_money_with_symbol(@cart.sub_total) %></h3>
      <%= form_tag orders_path do %>
        <%= hidden_field_tag 'cart_id', @cart.id %>
        <%= submit_tag 'Checkout', class: 'btn-green' %>
      <% end %>
      <br>
      <%= link_to "Limpar", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}, class: 'btn-red' %>
    </div>
</div>
<% end %>

<div class="container mt-2" style="margin-bottom: 10%">
  <div class="row d-flex justify-content-center">
    <div class="col-align-self-center">
      <div style="margin-top: 15em">
            <%= link_to "Produtos", products_path, class: "btn btn-outline-dark"%>
      </div>
    </div>
  </div>
</div>

</div>