config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  get 'about', to: 'pages#about'
  get 'contacts', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
  
  get 'tags/:tag', to: 'products#index', as: :tag


  post 'line_items/:id/add', to: 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items', to: 'line_items#create'
  get 'line_items/:id', to: 'line_items#show', as: 'line_item'
  delete 'line_items/:id', to: 'line_items#destroy'


  get "profile", to: "pages#profile", as: "profile"

  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo

  has_many :reviews, dependent: :nullify
  has_many :taggings
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by!(name: name).products
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  monetize :price_cents

  self.per_page = 4

  include PgSearch::Model
  pg_search_scope :search_by_full_name, against: [:name]
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:term]
      @products = Product.search_by_full_name(params[:term])
    elsif
      params[:tag] ? @products = Product.tagged_with(params[:tag]) : @products = Product.all
    else
      @products = Product.all
    end
     @products = Product.paginate(page: params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end



  private

  def product_params
    params.require(:product).permit()
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/views/products/_reviews_form.html.erb
<%= simple_form_for [product, review] do |f| %>
  <h3>Escreva o seu comentário:</h3>
  <%= f.input :description %>
  <%= f.button :submit, "Enviar", class: "btn btn-outline-success" %>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
<% end %>

app/views/products/index.html.erb
<div class="indexfullpage">
<div class="search-bar">
  <%= form_tag products_path, method: :get, class: "search-bar" do %>
    <%= text_field_tag 'term', params[:term], options = {style:"height:40px;border-radius:10px", placeholder: "Procure o seu produto"} %>
    <%= submit_tag 'Procurar', class: "btn-main" %>
  <% end %>
</div>

<div class="pagination">
    <div class="digg_pagination">
        <%= will_paginate @products %> 
    </div>
</div>

<div class="container">
 <div class="row">
    <% @products.order('name ASC').each do |product| %>
     <div class="column">
      <div class="d-flex justify-content-center" style="margin-top: 10%">
        <div class="image-box">
        <%= link_to product_path(product.id) do %>
          <%= cl_image_tag product.photo.key, height: 400, width: 500, crop: :thumb %>
        <% end %>
        </div>
      </div>
         <div class="card-body">
           <div class="justify-content-center">

               <h3 class="card-title"><%= product.name %></h3>

               <h6 class="card-text"><%= product.description %></h6>

               <h5 class="card-text" style="justify-content: center"><u>Preço</u>: <%= humanized_money_with_symbol(product.price) %></h5>     
               <p>Categoria:<strong> <%= raw product.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %> </strong </p>
           </div>
         </div>
       </div>
    <% end %>
  </div>
 </div>
</div>

<div class="pagination">
    <div class="digg_pagination">
        <%= will_paginate @products %> 
    </div>
</div>

<div class="container mt-2" style="margin-bottom: 10%">
  <div class="row d-flex justify-content-center">
    <div class="col-align-self-center">
      <div style="margin-top: 50%">
            <%= link_to "Voltar", root_path, class: "btn btn-outline-dark"%>
      </div>
    </div>
  </div>
</div>

</div>

app/views/products/show.html.erb
<div class="showfullpage">
 <div class="productshow">
  <div class="container py-3" style="margin-top: 7%">
    <div class="row">
      <div class="col-sm-12 col-md-6">
           <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :thumb %>
      </div>
      <div class="col-sm-12 col-md-6">
        <h1><%= @product.name %></h1>
        <h6><%= @product.description %></h6>
        <br>
        <p><%= @product.extended_description %></p>
        <h5><strong>Preço: <%= humanized_money_with_symbol(@product.price) %></h5></strong>
        <p>Tags: <%= raw @product.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></p>
        <%= button_to "Adicionar ao carrinho", line_items_path(product_id: @product.id), class: 'btn-green btn-sm' %>

        <!--
        <%= form_tag orders_path do %>
          <%= hidden_field_tag 'product_id', @product.id %>
          <%= submit_tag 'Comprar', class: 'btn btn-success' %>
        <% end %> -->
      </div>
    </div>
  </div>
</div>


<% if user_signed_in? %>
   <div class="row d-flex justify-content-center">
     <div style="margin-top: 100px">
       <span id="button-book" style="z-index: 2" data-toggle="modal" data-target="#product-<%= @product.id %>">
         <button type="button" class="btn-purple btn-sm">Adicione um comentário</button>
      </span>
     </div>
   </div>
<% end %>

</div>


 <div id="comment_title">
   <h4>Comentários:</h4>
 </div>

<% if @product.reviews.empty? %>
  <div class="row d-flex justify-content-center">
   <h6>Este produto ainda não tem comentários</h6>
  </div>
<% else %>
    <div class="review_box">
     <% @product.reviews.each do |review| %>
       <div class="row d-flex justify-content-center">
         <div class="card" style="width: 30rem;">
           <div class="list-group list-group-flush">
            <% if review.user.first_name.present? && review.user.last_name.present? %>
              <h5>O utilizador/a <strong><%= review.user.first_name %> <%= review.user.last_name %></strong> escreveu:</h5>
            <% else %>
              <h5>O utilizador/a <strong> <%= review.user.email %> </strong> escreveu:</h5>
            <% end %>
             <li><%= review.description %></li>
             <li><u><%= review.created_at %></u></li>
           </div>
         </div>
       </div>
     <% end %>
    </div>
<% end %>
<!-- REVIEWS MODAL -->

 <div class="modal fade" id="product-<%= @product.id%>" tabindex="-1" role="dialog" aria-labelledby="product-<%= @product.id%>titlelabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="product-<%= @product.id%>titlelabel" >Escreva o seu comentário: </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render "reviews_form", review: Review.new, product: @product %>
          </div>
        </div>
      </div>
    </div>








<div class="container mt-2" style="margin-bottom: 10%">
  <div class="row d-flex justify-content-center">
    <div class="col-align-self-center">
      <div style="margin-top: 30%">
            <%= link_to "Back", products_path, class: "btn btn-outline-dark"%>
      </div>
    </div>
  </div>
</div>